In [86]:
import pandas as pd
filename = "auto-mpg.txt"
column_names = ['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'Model year','Origin', 'mpg']
df = pd.read_csv(filename, sep=',', names=column_names)

print (df.shape)
df.head(5)


(398, 8)


cylinders  displacement horsepower  weight  acceleration  Model year  \
0          8         307.0        130    3504          12.0          70   
1          8         350.0        165    3693          11.5          70   
2          8         318.0        150    3436          11.0          70   
3          8         304.0        150    3433          12.0          70   
4          8         302.0        140    3449          10.5          70   

   Origin   mpg  
0       1  18.0  
1       1  15.0  
2       1  18.0  
3       1  16.0  
4       1  17.0

In [87]:

horsepower_missing_ind = df[df.horsepower=='?'].index
df.loc[horsepower_missing_ind]
Cylinders=[8,4,6,3,5]

def label_race (row,col_name,value):
    if row[col_name] == value :
        return 1
    else:
        return 0
for value in Cylinders:
    df['Cylinder_'+str(value)]=df.apply (lambda row: label_race (row,'cylinders',value),axis=1)

Model=[70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82]

for value in Model:
    df['Model_'+str(value)]=df.apply (lambda row: label_race (row,'Model year',value),axis=1)
    
Origin=[1,2,3]

for value in Origin:
    df['Origin_'+str(value)]=df.apply (lambda row: label_race (row,'Origin',value),axis=1)
df

cylinders  displacement horsepower  weight  acceleration  Model year  \
0            8         307.0        130    3504          12.0          70   
1            8         350.0        165    3693          11.5          70   
2            8         318.0        150    3436          11.0          70   
3            8         304.0        150    3433          12.0          70   
4            8         302.0        140    3449          10.5          70   
5            8         429.0        198    4341          10.0          70   
6            8         454.0        220    4354           9.0          70   
7            8         440.0        215    4312           8.5          70   
8            8         455.0        225    4425          10.0          70   
9            8         390.0        190    3850           8.5          70   
10           8         383.0        170    3563          10.0          70   
11           8         340.0        160    3609           8.0          70   
12           8         400.0        150    3761           9.5          70   
13           8         455.0        225    3086          10.0          70   
14           4         113.0         95    2372          15.0          70   
15           6         198.0         95    2833          15.5          70   
16           6         199.0         97    2774          15.5          70   
17           6         200.0         85    2587          16.0          70   
18           4          97.0         88    2130          14.5          70   
19           4          97.0         46    1835          20.5          70   
20           4         110.0         87    2672          17.5          70   
21           4         107.0         90    2430          14.5          70   
22           4         104.0         95    2375          17.5          70   
23           4         121.0        113    2234          12.5          70   
24           6         199.0         90    2648          15.0          70   
25           8         360.0        215    4615          14.0          70   
26           8         307.0        200    4376          15.0          70   
27           8         318.0        210    4382          13.5          70   
28           8         304.0        193    4732          18.5          70   
29           4          97.0         88    2130          14.5          71   
..         ...           ...        ...     ...           ...         ...   
368          4         112.0         88    2640          18.6          82   
369          4         112.0         88    2395          18.0          82   
370          4         112.0         85    2575          16.2          82   
371          4         135.0         84    2525          16.0          82   
372          4         151.0         90    2735          18.0          82   
373          4         140.0         92    2865          16.4          82   
374          4         151.0          ?    3035          20.5          82   
375          4         105.0         74    1980          15.3          82   
376          4          91.0         68    2025          18.2          82   
377          4          91.0         68    1970          17.6          82   
378          4         105.0         63    2125          14.7          82   
379          4          98.0         70    2125          17.3          82   
380          4         120.0         88    2160          14.5          82   
381          4         107.0         75    2205          14.5          82   
382          4         108.0         70    2245          16.9          82   
383          4          91.0         67    1965          15.0          82   
384          4          91.0         67    1965          15.7          82   
385          4          91.0         67    1995          16.2          82   
386          6         181.0        110    2945          16.4          82   
387          6         262.0         85    3015          17.0          82   
3

In [88]:

df.loc[horsepower_missing_ind, 'horsepower'] = float('nan')
df.horsepower = df.horsepower.apply(pd.to_numeric)
df.loc[horsepower_missing_ind, 'horsepower'] = int( df.horsepower.mean() )
pd.set_option('precision', 2)
#drop columns which are multi-valued
df=df.drop(['cylinders','Model year','Origin'],axis=1)
#rearrange column position
cols = df.columns.tolist()
cols=cols[:3]+cols[5:]
cols.append('mpg')
df = df[cols]
#df
df

displacement  horsepower  weight  Cylinder_8  Cylinder_4  Cylinder_6  \
0           307.0       130.0    3504           1           0           0   
1           350.0       165.0    3693           1           0           0   
2           318.0       150.0    3436           1           0           0   
3           304.0       150.0    3433           1           0           0   
4           302.0       140.0    3449           1           0           0   
5           429.0       198.0    4341           1           0           0   
6           454.0       220.0    4354           1           0           0   
7           440.0       215.0    4312           1           0           0   
8           455.0       225.0    4425           1           0           0   
9           390.0       190.0    3850           1           0           0   
10          383.0       170.0    3563           1           0           0   
11          340.0       160.0    3609           1           0           0   
12          400.0       150.0    3761           1           0           0   
13          455.0       225.0    3086           1           0           0   
14          113.0        95.0    2372           0           1           0   
15          198.0        95.0    2833           0           0           1   
16          199.0        97.0    2774           0           0           1   
17          200.0        85.0    2587           0           0           1   
18           97.0        88.0    2130           0           1           0   
19           97.0        46.0    1835           0           1           0   
20          110.0        87.0    2672           0           1           0   
21          107.0        90.0    2430           0           1           0   
22          104.0        95.0    2375           0           1           0   
23          121.0       113.0    2234           0           1           0   
24          199.0        90.0    2648           0           0           1   
25          360.0       215.0    4615           1           0           0   
26          307.0       200.0    4376           1           0           0   
27          318.0       210.0    4382           1           0           0   
28          304.0       193.0    4732           1           0           0   
29           97.0        88.0    2130           0           1           0   
..            ...         ...     ...         ...         ...         ...   
368         112.0        88.0    2640           0           1           0   
369         112.0        88.0    2395           0           1           0   
370         112.0        85.0    2575           0           1           0   
371         135.0        84.0    2525           0           1           0   
372         151.0        90.0    2735           0           1           0   
373         140.0        92.0    2865           0           1           0   
374         151.0       104.0    3035           0           1           0   
375         105.0        74.0    1980           0           1           0   
376          91.0        68.0    2025           0           1           0   
377          91.0        68.0    1970           0           1           0   
378         105.0        63.0    2125           0           1           0   
379          98.0        70.0    2125           0           1           0   
380         120.0        88.0    2160           0           1           0   
381         107.0        75.0    2205           0           1           0   
382         108.0        70.0    2245           0           1           0   
383          91.0        67.0    1965           0           1           0   
384          91.0        67.0    1965           0           1           0   
385          91.0        67.0    1995           0           1           0   
386         181.0       110.0    2945           0           0           1   
387         262.0        85.0    3015           0           0           1   
3

In [104]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt
from matplotlib import rcParams
rcParams["figure.figsize"]=10,5
%matplotlib inline

In [135]:
x=df.loc[:, 'displacement':'Origin_3']
y = np.asarray(df['mpg'], dtype="|S6")
test_size=0.3
random_state=3
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=test_size,random_state=random_state)
sc = StandardScaler()

X_train_std = sc.fit(x_train)
X_test_std=sc.fit(x_test)


unique labels: [b'10.0' b'11.0' b'12.0' b'13.0' b'14.0' b'14.5' b'15.0' b'15.5' b'16.0'
 b'16.2' b'16.5' b'16.9' b'17.0' b'17.5' b'17.6' b'17.7' b'18.0' b'18.1'
 b'18.2' b'18.5' b'18.6' b'19.0' b'19.1' b'19.2' b'19.4' b'19.8' b'19.9'
 b'20.0' b'20.2' b'20.3' b'20.5' b'20.6' b'20.8' b'21.0' b'21.1' b'21.5'
 b'21.6' b'22.0' b'22.3' b'22.4' b'22.5' b'23.0' b'23.2' b'23.5' b'23.6'
 b'23.7' b'23.8' b'23.9' b'24.0' b'24.2' b'24.3' b'24.5' b'25.0' b'25.1'
 b'25.4' b'25.5' b'25.8' b'26.0' b'26.4' b'26.5' b'26.6' b'26.8' b'27.0'
 b'27.2' b'27.4' b'27.5' b'27.9' b'28.0' b'28.1' b'28.4' b'28.8' b'29.0'
 b'29.5' b'29.8' b'29.9' b'30.0' b'30.5' b'30.7' b'30.9' b'31.0' b'31.3'
 b'31.5' b'31.6' b'31.8' b'31.9' b'32.0' b'32.1' b'32.2' b'32.3' b'32.4'
 b'32.7' b'32.8' b'32.9' b'33.0' b'33.5' b'33.7' b'33.8' b'34.0' b'34.1'
 b'34.2' b'34.3' b'34.4' b'34.5' b'34.7' b'35.0' b'35.1' b'35.7' b'36.0'
 b'36.1' b'36.4' b'37.0' b'37.2' b'37.3' b'37.7' b'38.0' b'38.1' b'39.0'
 b'39.1' b'39.4' b'40.8' b'40.9' b'4

array([18. , 15. , 16. , 17. , 14. , 24. , 22. , 21. , 27. , 26. , 25. ,
       10. , 11. ,  9. , 28. , 19. , 12. , 13. , 23. , 30. , 31. , 35. ,
       20. , 29. , 32. , 33. , 17.5, 15.5, 14.5, 22.5, 24.5, 18.5, 29.5,
       26.5, 16.5, 31.5, 36. , 25.5, 33.5, 20.5, 30.5, 21.5, 43.1, 36.1,
       32.8, 39.4, 19.9, 19.4, 20.2, 19.2, 25.1, 20.6, 20.8, 18.6, 18.1,
       17.7, 27.5, 27.2, 30.9, 21.1, 23.2, 23.8, 23.9, 20.3, 21.6, 16.2,
       19.8, 22.3, 17.6, 18.2, 16.9, 31.9, 34.1, 35.7, 27.4, 25.4, 34.2,
       34.5, 31.8, 37.3, 28.4, 28.8, 26.8, 41.5, 38.1, 32.1, 37.2, 26.4,
       24.3, 19.1, 34.3, 29.8, 31.3, 37. , 32.2, 46.6, 27.9, 40.8, 44.3,
       43.4, 36.4, 44.6, 40.9, 33.8, 32.7, 23.7, 23.6, 32.4, 26.6, 25.8,
       23.5, 39.1, 39. , 35.1, 32.3, 37.7, 34.7, 34.4, 29.9, 33.7, 32.9,
       31.6, 28.1, 30.7, 24.2, 22.4, 34. , 38. , 44. ])

In [3]:
import numpy as np
from numpy import linalg as la

a = [[1,2],[3,4],[5,6]]
w = [2,0]
x = np.array([1,1,1,1])
x1 = np.array([1.001,1.001,1.001, 1.001])
print(abs(la.norm(x,2) - la.norm(x1,2)))
w = np.array(w)
print(w)
for e in a:
    x1 = np.array(e).reshape((-1,1))
    print(x1.shape)
    print(np.dot(w,x1))
f = lambda x:1 if x > 0 else 0
print(f(2))
w + np.array([2,2])

0.0019999999999997797
[2 0]
(2, 1)
[2]
(2, 1)
[6]
(2, 1)
[10]
1


array([4, 2])

In [9]:
import numpy as np
a = np.array([1,2,3])
b = np.array([1,2,3])
a @ b
4//3
a/1

array([1., 2., 3.])