In [468]:
import numpy as np
import random


def pocket(data_vec,Learning_rate_n,m):
    Wpk,Wpe = np.random.rand(1,data_vec.shape[1]),np.random.rand(1,data_vec.shape[1])
    rpk,rpe,Pkt,Ppe,n= 0,0,0,0,m
    data_vec[data_vec == 0] = -1
    for i in range(m):
        r = random.randint(0,data_vec.shape[1])        
        if(dataset[r,-1]*(np.dot(dataset[r,:-1],Wpe[0,1:])+Wpe[0,0]) > 0): # correct 
            rpe += 1
            
            if(rpe > rpk):
                Ppe = rpe
            if(Ppe > Pkt):
                Wpk = Wpe.copy()
                rpk = rpe
                Pkt = Ppe
                if(Pkt == data_vec.shape[0]):
                    n = i + 1
                    break
        else:
            Wpe[0,0] = Wpe[0,0]*Learning_rate_n*data_vec[r,-1]
            Wpe[0,1:] = Wpe[0,1:] + Learning_rate_n*dataset[r,:-1]*Wpe[0,1:]
            rpe = 0 
    rate =(np.dot(data_vec[:,:-1],Wpk[0,1:])+ Wpk[0,0])*data_vec[:,-1]
    rate = sign(rate)
    rate[rate == -1] = 0
    rate = sum(rate)/rate.shape[0]
    return rate,Wpk,n

In [478]:
dataset = np.array([[0,0,0],
                    [0,0,0],
                    [1,1,1],
                    [0,1,1],
                    [1,0,1],
                    [1,1,1],
                    [0,1,1],
                    [1,0,1],
                    [0,0,0],
                    [0,0,0],
                    [1,1,1],
                    [0,1,1],
                    [1,0,1],
                    [0,0,0],
                    [0,0,0],
                    [1,1,1],
                    [1,1,1],
                    [0,0,0],
                    [1,1,1]])   # OR function


rate,Wpk,n= pocket(dataset,0.2,50)
dataset[dataset == 0] = -1
print(dataset)
print(Wpk)

rate,Wpk,n

[[-1 -1 -1]
 [-1 -1 -1]
 [ 1  1  1]
 [-1  1  1]
 [ 1 -1  1]
 [ 1  1  1]
 [-1  1  1]
 [ 1 -1  1]
 [-1 -1 -1]
 [-1 -1 -1]
 [ 1  1  1]
 [-1  1  1]
 [ 1 -1  1]
 [-1 -1 -1]
 [-1 -1 -1]
 [ 1  1  1]
 [ 1  1  1]
 [-1 -1 -1]
 [ 1  1  1]]
[[-0.19944072  0.22018888  0.4460876 ]]


(0.8421052631578947, array([[-0.19944072,  0.22018888,  0.4460876 ]]), 20)

In [477]:
dataset = np.array([[0,0,0],
                    [0,0,0],
                    [0,1,0],
                    [0,1,0],
                    [1,0,0],
                    [1,0,0],
                    [1,1,1],
                    [1,1,1],
                    [1,1,1],
                    [1,0,0],
                    [1,0,0],
                    [1,0,0],
                    [1,0,0],
                    [1,1,1],
                    [1,1,1],
                    [1,1,1],
                    [1,1,1],
                    [1,1,1],
                    [1,1,1],
                    [1,0,0],
                    [1,1,1],
                    [1,1,1],
                    [1,1,1],
                    [1,0,0],
                    [1,0,0],
                    [1,1,1],
                    [1,1,1],
                    [1,1,1],
                    [1,0,0],
                    [1,1,1],
                    [1,1,1],
                    [1,1,1],
                    [1,0,0]
                   ])          # AND function
rate,Wpk,n = pocket(dataset,0.2,50)
dataset[dataset == 0] = -1
print(dataset)
print(Wpk)


rate,Wpk,n

[[-1 -1 -1]
 [-1 -1 -1]
 [-1  1 -1]
 [-1  1 -1]
 [ 1 -1 -1]
 [ 1 -1 -1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1 -1 -1]
 [ 1 -1 -1]
 [ 1 -1 -1]
 [ 1 -1 -1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1 -1 -1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1 -1 -1]
 [ 1 -1 -1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1 -1 -1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1 -1 -1]]
[[-0.052053    0.20720527  0.16986473]]


(1.0, array([[-0.052053  ,  0.20720527,  0.16986473]]), 35)

In [487]:
dataset = np.array([[0,0,0],
                    [0,1,1],
                    [1,0,1],
                    [1,1,0],
                    [0,1,1],
                    [1,0,1],
                    [1,1,0],
                    [0,1,1],
                    [1,0,1],
                    [1,1,0],
                    [0,1,1],
                    [1,0,1],
                    [1,1,0],
                    [1,1,0],
                    [0,1,1],
                    [1,0,1],
                    [1,1,0],
                    [0,1,1],
                    [1,0,1],
                    [1,1,0],
                    [1,1,0],
                    [0,1,1],
                    [1,0,1],
                    [1,1,0],
                    [0,1,1],
                    [1,0,1],   # XOR function
                    [1,1,0]
                   ])
rate,Wpk,n = pocket(dataset,0.01,20000)
dataset[dataset == 0] = -1
print(dataset)
print(Wpk)

rate,Wpk,n

[[-1 -1 -1]
 [-1  1  1]
 [ 1 -1  1]
 [ 1  1 -1]
 [-1  1  1]
 [ 1 -1  1]
 [ 1  1 -1]
 [-1  1  1]
 [ 1 -1  1]
 [ 1  1 -1]
 [-1  1  1]
 [ 1 -1  1]
 [ 1  1 -1]
 [ 1  1 -1]
 [-1  1  1]
 [ 1 -1  1]
 [ 1  1 -1]
 [-1  1  1]
 [ 1 -1  1]
 [ 1  1 -1]
 [ 1  1 -1]
 [-1  1  1]
 [ 1 -1  1]
 [ 1  1 -1]
 [-1  1  1]
 [ 1 -1  1]
 [ 1  1 -1]]
[[0.00000000e+00 1.10033836e+10 1.10965888e+10]]


(0.3333333333333333,
 array([[0.00000000e+00, 1.10033836e+10, 1.10965888e+10]]),
 20000)

In [ ]:
def MLP_pocket(data_vec,fraction_v,Learning_rate_n,m):
    r,w,n = pocket(data_vec,Learning_rate_n,m)
    N = w

In [ ]:
def add_neuron_to_first_hidden_layer(data_vec):
    

In [ ]:
def 